language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - rbx-2.5.2
services:
  - postgresql
before_script:
  - psql -c 'create database lookup_by_test' -U postgres
script:
  - bundle exec rake app:db:test:prepare
  - bundle exec appraisal install
  - bundle exec appraisal rake
