language: ruby
rvm:
  - 1.9.3-p551
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - rbx-3.19
services:
  - postgresql
before_script:
  - psql -c 'create database lookup_by_test' -U postgres
script:
  - bundle exec rake app:db:test:prepare
  - bundle exec appraisal install
  - bundle exec appraisal rake
