language: ruby

cache:
  bundler: true

rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.1

services:
  - postgresql

# Travis defaults to PostgreSQL 9.1
addons:
  postgresql: "9.4"

script:
  - bundle exec appraisal install
  - bundle exec appraisal rake

general:
  artifacts:
    - coverage
