language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0-preview1
  - ruby-head
  - rbx
  - rbx-2.2.2
services:
  - postgresql
before_script:
  - psql -c 'create database lookup_by_test' -U postgres
script:
  - bundle exec rake app:db:test:prepare
  - bundle exec rake
